# permissions for end users to edit aompolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aompolicy-editor-role
rules:
- apiGroups:
  - itmonkey.itmonkey.icu
  resources:
  - aompolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - itmonkey.itmonkey.icu
  resources:
  - aompolicies/status
  verbs:
  - get
