# permissions for end users to view aompolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aompolicy-viewer-role
rules:
- apiGroups:
  - itmonkey.itmonkey.icu
  resources:
  - aompolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - itmonkey.itmonkey.icu
  resources:
  - aompolicies/status
  verbs:
  - get
