---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - itmonkey.itmonkey.icu
  resources:
  - aomgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - itmonkey.itmonkey.icu
  resources:
  - aomgroups/finalizers
  verbs:
  - update
- apiGroups:
  - itmonkey.itmonkey.icu
  resources:
  - aomgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - itmonkey.itmonkey.icu
  resources:
  - aompolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - itmonkey.itmonkey.icu
  resources:
  - aompolicies/finalizers
  verbs:
  - update
- apiGroups:
  - itmonkey.itmonkey.icu
  resources:
  - aompolicies/status
  verbs:
  - get
  - patch
  - update
